 HEAD
# .streamlit/config.toml
[server]
headless = true
port = 8501
enableCORS = false
[server]
headless = true
port = 8501
enableCORS = false 
4dcba67 (Rename main.py to streamlit_app.py and add Streamlit config)
